CREATE PROC FI_SP_IncBenef
    @NOME          VARCHAR (50),
	@CPF           VARCHAR (11),
	@IDCliente           BIGINT
AS
BEGIN

INSERT INTO BENEFICIARIOS(NOME, CPF, IDCLIENTE) 
	VALUES (@NOME, @CPF,@IDCliente)
	SELECT SCOPE_IDENTITY()

END